/*
 * Icon.js
 */

const icons = {
  'application-x-executable-symbolic': require('./assets/icons/application-x-executable-symbolic.svg'),
  'audio-volume-high-symbolic': require('./assets/icons/audio-volume-high-symbolic.svg'),
  'audio-volume-low-symbolic': require('./assets/icons/audio-volume-low-symbolic.svg'),
  'audio-volume-medium-symbolic': require('./assets/icons/audio-volume-medium-symbolic.svg'),
  'audio-volume-muted-symbolic': require('./assets/icons/audio-volume-muted-symbolic.svg'),
  'bookmark-new-symbolic': require('./assets/icons/bookmark-new-symbolic.svg'),
  'caps-lock-symbolic': require('./assets/icons/caps-lock-symbolic.svg'),
  'changes-allow-symbolic': require('./assets/icons/changes-allow-symbolic.svg'),
  'changes-prevent-symbolic': require('./assets/icons/changes-prevent-symbolic.svg'),
  'color-select-symbolic': require('./assets/icons/color-select-symbolic.svg'),
  'dialog-error-symbolic': require('./assets/icons/dialog-error-symbolic.svg'),
  'dialog-information-symbolic': require('./assets/icons/dialog-information-symbolic.svg'),
  'dialog-password-symbolic': require('./assets/icons/dialog-password-symbolic.svg'),
  'dialog-question-symbolic': require('./assets/icons/dialog-question-symbolic.svg'),
  'dialog-warning-symbolic': require('./assets/icons/dialog-warning-symbolic.svg'),
  'document-open-recent-symbolic': require('./assets/icons/document-open-recent-symbolic.svg'),
  'document-open-symbolic': require('./assets/icons/document-open-symbolic.svg'),
  'document-save-as-symbolic': require('./assets/icons/document-save-as-symbolic.svg'),
  'document-save-symbolic': require('./assets/icons/document-save-symbolic.svg'),
  'drive-harddisk-symbolic': require('./assets/icons/drive-harddisk-symbolic.svg'),
  'edit-clear-all-symbolic': require('./assets/icons/edit-clear-all-symbolic.svg'),
  'edit-clear-symbolic': require('./assets/icons/edit-clear-symbolic.svg'),
  'edit-copy-symbolic': require('./assets/icons/edit-copy-symbolic.svg'),
  'edit-cut-symbolic': require('./assets/icons/edit-cut-symbolic.svg'),
  'edit-delete-symbolic': require('./assets/icons/edit-delete-symbolic.svg'),
  'edit-find-symbolic': require('./assets/icons/edit-find-symbolic.svg'),
  'edit-paste-symbolic': require('./assets/icons/edit-paste-symbolic.svg'),
  'edit-select-all-symbolic': require('./assets/icons/edit-select-all-symbolic.svg'),
  'emblem-important-symbolic': require('./assets/icons/emblem-important-symbolic.svg'),
  'emblem-system-symbolic': require('./assets/icons/emblem-system-symbolic.svg'),
  'emoji-activities-symbolic': require('./assets/icons/emoji-activities-symbolic.svg'),
  'emoji-body-symbolic': require('./assets/icons/emoji-body-symbolic.svg'),
  'emoji-flags-symbolic': require('./assets/icons/emoji-flags-symbolic.svg'),
  'emoji-food-symbolic': require('./assets/icons/emoji-food-symbolic.svg'),
  'emoji-nature-symbolic': require('./assets/icons/emoji-nature-symbolic.svg'),
  'emoji-objects-symbolic': require('./assets/icons/emoji-objects-symbolic.svg'),
  'emoji-people-symbolic': require('./assets/icons/emoji-people-symbolic.svg'),
  'emoji-recent-symbolic': require('./assets/icons/emoji-recent-symbolic.svg'),
  'emoji-symbols-symbolic': require('./assets/icons/emoji-symbols-symbolic.svg'),
  'emoji-travel-symbolic': require('./assets/icons/emoji-travel-symbolic.svg'),
  'eye-not-looking-symbolic': require('./assets/icons/eye-not-looking-symbolic.svg'),
  'eye-open-negative-filled-symbolic': require('./assets/icons/eye-open-negative-filled-symbolic.svg'),
  'face-smile-big-symbolic': require('./assets/icons/face-smile-big-symbolic.svg'),
  'face-smile-symbolic': require('./assets/icons/face-smile-symbolic.svg'),
  'find-location-symbolic': require('./assets/icons/find-location-symbolic.svg'),
  'folder-documents-symbolic': require('./assets/icons/folder-documents-symbolic.svg'),
  'folder-download-symbolic': require('./assets/icons/folder-download-symbolic.svg'),
  'folder-music-symbolic': require('./assets/icons/folder-music-symbolic.svg'),
  'folder-new-symbolic': require('./assets/icons/folder-new-symbolic.svg'),
  'folder-pictures-symbolic': require('./assets/icons/folder-pictures-symbolic.svg'),
  'folder-publicshare-symbolic': require('./assets/icons/folder-publicshare-symbolic.svg'),
  'folder-remote-symbolic': require('./assets/icons/folder-remote-symbolic.svg'),
  'folder-saved-search-symbolic': require('./assets/icons/folder-saved-search-symbolic.svg'),
  'folder-symbolic': require('./assets/icons/folder-symbolic.svg'),
  'folder-templates-symbolic': require('./assets/icons/folder-templates-symbolic.svg'),
  'folder-videos-symbolic': require('./assets/icons/folder-videos-symbolic.svg'),
  'insert-image-symbolic': require('./assets/icons/insert-image-symbolic.svg'),
  'insert-object-symbolic': require('./assets/icons/insert-object-symbolic.svg'),
  'list-add-symbolic': require('./assets/icons/list-add-symbolic.svg'),
  'list-remove-all-symbolic': require('./assets/icons/list-remove-all-symbolic.svg'),
  'list-remove-symbolic': require('./assets/icons/list-remove-symbolic.svg'),
  'media-eject-symbolic': require('./assets/icons/media-eject-symbolic.svg'),
  'media-playback-pause-symbolic': require('./assets/icons/media-playback-pause-symbolic.svg'),
  'media-playback-start-symbolic-rtl': require('./assets/icons/media-playback-start-symbolic-rtl.svg'),
  'media-playback-start-symbolic': require('./assets/icons/media-playback-start-symbolic.svg'),
  'media-playback-stop-symbolic': require('./assets/icons/media-playback-stop-symbolic.svg'),
  'media-playlist-repeat-symbolic': require('./assets/icons/media-playlist-repeat-symbolic.svg'),
  'media-record-symbolic': require('./assets/icons/media-record-symbolic.svg'),
  'network-server-symbolic': require('./assets/icons/network-server-symbolic.svg'),
  'network-workgroup-symbolic': require('./assets/icons/network-workgroup-symbolic.svg'),
  'object-select-symbolic': require('./assets/icons/object-select-symbolic.svg'),
  'open-menu-symbolic': require('./assets/icons/open-menu-symbolic.svg'),
  'orientation-landscape-inverse-symbolic': require('./assets/icons/orientation-landscape-inverse-symbolic.svg'),
  'orientation-landscape-symbolic': require('./assets/icons/orientation-landscape-symbolic.svg'),
  'orientation-portrait-inverse-symbolic': require('./assets/icons/orientation-portrait-inverse-symbolic.svg'),
  'orientation-portrait-symbolic': require('./assets/icons/orientation-portrait-symbolic.svg'),
  'pan-down-symbolic': require('./assets/icons/pan-down-symbolic.svg'),
  'pan-end-symbolic-rtl': require('./assets/icons/pan-end-symbolic-rtl.svg'),
  'pan-end-symbolic': require('./assets/icons/pan-end-symbolic.svg'),
  'pan-start-symbolic-rtl': require('./assets/icons/pan-start-symbolic-rtl.svg'),
  'pan-start-symbolic': require('./assets/icons/pan-start-symbolic.svg'),
  'pan-up-symbolic': require('./assets/icons/pan-up-symbolic.svg'),
  'process-working-symbolic': require('./assets/icons/process-working-symbolic.svg'),
  'switch-off': require('./assets/icons/switch-off.symbolic.svg'),
  'switch-on': require('./assets/icons/switch-on.symbolic.svg'),
  'user-desktop-symbolic': require('./assets/icons/user-desktop-symbolic.svg'),
  'user-home-symbolic': require('./assets/icons/user-home-symbolic.svg'),
  'user-trash-symbolic': require('./assets/icons/user-trash-symbolic.svg'),
  'view-list-symbolic': require('./assets/icons/view-list-symbolic.svg'),
  'view-more-symbolic': require('./assets/icons/view-more-symbolic.svg'),
  'view-refresh-symbolic': require('./assets/icons/view-refresh-symbolic.svg'),
  'window-close-symbolic': require('./assets/icons/window-close-symbolic.svg'),
  'window-maximize-symbolic': require('./assets/icons/window-maximize-symbolic.svg'),
  'window-minimize-symbolic': require('./assets/icons/window-minimize-symbolic.svg'),
  'window-restore-symbolic': require('./assets/icons/window-restore-symbolic.svg'),
}

function Icon({ name }) {
  return (
    <span className='Icon'>
      <img src={icons[name].default} />
    </span>
  )
}

export default Icon
